// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/karatekaneen/stockybot/ent/predicate"
	"github.com/karatekaneen/stockybot/ent/security"
	"github.com/karatekaneen/stockybot/ent/watch"
)

// WatchQuery is the builder for querying Watch entities.
type WatchQuery struct {
	config
	ctx          *QueryContext
	order        []watch.OrderOption
	inters       []Interceptor
	predicates   []predicate.Watch
	withWatching *SecurityQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WatchQuery builder.
func (wq *WatchQuery) Where(ps ...predicate.Watch) *WatchQuery {
	wq.predicates = append(wq.predicates, ps...)
	return wq
}

// Limit the number of records to be returned by this query.
func (wq *WatchQuery) Limit(limit int) *WatchQuery {
	wq.ctx.Limit = &limit
	return wq
}

// Offset to start from.
func (wq *WatchQuery) Offset(offset int) *WatchQuery {
	wq.ctx.Offset = &offset
	return wq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wq *WatchQuery) Unique(unique bool) *WatchQuery {
	wq.ctx.Unique = &unique
	return wq
}

// Order specifies how the records should be ordered.
func (wq *WatchQuery) Order(o ...watch.OrderOption) *WatchQuery {
	wq.order = append(wq.order, o...)
	return wq
}

// QueryWatching chains the current query on the "watching" edge.
func (wq *WatchQuery) QueryWatching() *SecurityQuery {
	query := (&SecurityClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(watch.Table, watch.FieldID, selector),
			sqlgraph.To(security.Table, security.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, watch.WatchingTable, watch.WatchingColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Watch entity from the query.
// Returns a *NotFoundError when no Watch was found.
func (wq *WatchQuery) First(ctx context.Context) (*Watch, error) {
	nodes, err := wq.Limit(1).All(setContextOp(ctx, wq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{watch.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wq *WatchQuery) FirstX(ctx context.Context) *Watch {
	node, err := wq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Watch ID from the query.
// Returns a *NotFoundError when no Watch ID was found.
func (wq *WatchQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wq.Limit(1).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{watch.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wq *WatchQuery) FirstIDX(ctx context.Context) int {
	id, err := wq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Watch entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Watch entity is found.
// Returns a *NotFoundError when no Watch entities are found.
func (wq *WatchQuery) Only(ctx context.Context) (*Watch, error) {
	nodes, err := wq.Limit(2).All(setContextOp(ctx, wq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{watch.Label}
	default:
		return nil, &NotSingularError{watch.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wq *WatchQuery) OnlyX(ctx context.Context) *Watch {
	node, err := wq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Watch ID in the query.
// Returns a *NotSingularError when more than one Watch ID is found.
// Returns a *NotFoundError when no entities are found.
func (wq *WatchQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wq.Limit(2).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{watch.Label}
	default:
		err = &NotSingularError{watch.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wq *WatchQuery) OnlyIDX(ctx context.Context) int {
	id, err := wq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Watches.
func (wq *WatchQuery) All(ctx context.Context) ([]*Watch, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryAll)
	if err := wq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Watch, *WatchQuery]()
	return withInterceptors[[]*Watch](ctx, wq, qr, wq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wq *WatchQuery) AllX(ctx context.Context) []*Watch {
	nodes, err := wq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Watch IDs.
func (wq *WatchQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wq.ctx.Unique == nil && wq.path != nil {
		wq.Unique(true)
	}
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryIDs)
	if err = wq.Select(watch.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wq *WatchQuery) IDsX(ctx context.Context) []int {
	ids, err := wq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wq *WatchQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryCount)
	if err := wq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wq, querierCount[*WatchQuery](), wq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wq *WatchQuery) CountX(ctx context.Context) int {
	count, err := wq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wq *WatchQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryExist)
	switch _, err := wq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wq *WatchQuery) ExistX(ctx context.Context) bool {
	exist, err := wq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WatchQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wq *WatchQuery) Clone() *WatchQuery {
	if wq == nil {
		return nil
	}
	return &WatchQuery{
		config:       wq.config,
		ctx:          wq.ctx.Clone(),
		order:        append([]watch.OrderOption{}, wq.order...),
		inters:       append([]Interceptor{}, wq.inters...),
		predicates:   append([]predicate.Watch{}, wq.predicates...),
		withWatching: wq.withWatching.Clone(),
		// clone intermediate query.
		sql:  wq.sql.Clone(),
		path: wq.path,
	}
}

// WithWatching tells the query-builder to eager-load the nodes that are connected to
// the "watching" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WatchQuery) WithWatching(opts ...func(*SecurityQuery)) *WatchQuery {
	query := (&SecurityClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withWatching = query
	return wq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WatchedSince time.Time `json:"watched_since,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Watch.Query().
//		GroupBy(watch.FieldWatchedSince).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wq *WatchQuery) GroupBy(field string, fields ...string) *WatchGroupBy {
	wq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WatchGroupBy{build: wq}
	grbuild.flds = &wq.ctx.Fields
	grbuild.label = watch.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WatchedSince time.Time `json:"watched_since,omitempty"`
//	}
//
//	client.Watch.Query().
//		Select(watch.FieldWatchedSince).
//		Scan(ctx, &v)
func (wq *WatchQuery) Select(fields ...string) *WatchSelect {
	wq.ctx.Fields = append(wq.ctx.Fields, fields...)
	sbuild := &WatchSelect{WatchQuery: wq}
	sbuild.label = watch.Label
	sbuild.flds, sbuild.scan = &wq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WatchSelect configured with the given aggregations.
func (wq *WatchQuery) Aggregate(fns ...AggregateFunc) *WatchSelect {
	return wq.Select().Aggregate(fns...)
}

func (wq *WatchQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wq); err != nil {
				return err
			}
		}
	}
	for _, f := range wq.ctx.Fields {
		if !watch.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wq.path != nil {
		prev, err := wq.path(ctx)
		if err != nil {
			return err
		}
		wq.sql = prev
	}
	return nil
}

func (wq *WatchQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Watch, error) {
	var (
		nodes       = []*Watch{}
		withFKs     = wq.withFKs
		_spec       = wq.querySpec()
		loadedTypes = [1]bool{
			wq.withWatching != nil,
		}
	)
	if wq.withWatching != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, watch.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Watch).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Watch{config: wq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wq.withWatching; query != nil {
		if err := wq.loadWatching(ctx, query, nodes, nil,
			func(n *Watch, e *Security) { n.Edges.Watching = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wq *WatchQuery) loadWatching(ctx context.Context, query *SecurityQuery, nodes []*Watch, init func(*Watch), assign func(*Watch, *Security)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Watch)
	for i := range nodes {
		if nodes[i].security_watchers == nil {
			continue
		}
		fk := *nodes[i].security_watchers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(security.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "security_watchers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (wq *WatchQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wq.querySpec()
	_spec.Node.Columns = wq.ctx.Fields
	if len(wq.ctx.Fields) > 0 {
		_spec.Unique = wq.ctx.Unique != nil && *wq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wq.driver, _spec)
}

func (wq *WatchQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(watch.Table, watch.Columns, sqlgraph.NewFieldSpec(watch.FieldID, field.TypeInt))
	_spec.From = wq.sql
	if unique := wq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wq.path != nil {
		_spec.Unique = true
	}
	if fields := wq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, watch.FieldID)
		for i := range fields {
			if fields[i] != watch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wq *WatchQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wq.driver.Dialect())
	t1 := builder.Table(watch.Table)
	columns := wq.ctx.Fields
	if len(columns) == 0 {
		columns = watch.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wq.sql != nil {
		selector = wq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wq.ctx.Unique != nil && *wq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wq.predicates {
		p(selector)
	}
	for _, p := range wq.order {
		p(selector)
	}
	if offset := wq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WatchGroupBy is the group-by builder for Watch entities.
type WatchGroupBy struct {
	selector
	build *WatchQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wgb *WatchGroupBy) Aggregate(fns ...AggregateFunc) *WatchGroupBy {
	wgb.fns = append(wgb.fns, fns...)
	return wgb
}

// Scan applies the selector query and scans the result into the given value.
func (wgb *WatchGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wgb.build.ctx, ent.OpQueryGroupBy)
	if err := wgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WatchQuery, *WatchGroupBy](ctx, wgb.build, wgb, wgb.build.inters, v)
}

func (wgb *WatchGroupBy) sqlScan(ctx context.Context, root *WatchQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wgb.fns))
	for _, fn := range wgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wgb.flds)+len(wgb.fns))
		for _, f := range *wgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WatchSelect is the builder for selecting fields of Watch entities.
type WatchSelect struct {
	*WatchQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ws *WatchSelect) Aggregate(fns ...AggregateFunc) *WatchSelect {
	ws.fns = append(ws.fns, fns...)
	return ws
}

// Scan applies the selector query and scans the result into the given value.
func (ws *WatchSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ws.ctx, ent.OpQuerySelect)
	if err := ws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WatchQuery, *WatchSelect](ctx, ws.WatchQuery, ws, ws.inters, v)
}

func (ws *WatchSelect) sqlScan(ctx context.Context, root *WatchQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ws.fns))
	for _, fn := range ws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
