// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Security is the predicate function for security builders.
type Security func(*sql.Selector)

// Watch is the predicate function for watch builders.
type Watch func(*sql.Selector)
